### ISSUE TITLE
Span.finish() does not call Segment.close()

### ISSUE THREAD

**Issue by dmytro-bekuzarov** [skylight-ipv/opentracing-java-aws-xray#2]
Hi guys,

Thanks for the implementation.

Can you please provide some examples on how to use this ? Because the code below does not work for me (the xray entity is in progress):
```
Span span = tracer.buildSpan("Request").start();
// some computation
span.finish();
```

I can't find in the code where the segment is ended.

**Comment by ashleymercer** [comment]
@dmytro-bekuzarov thanks for trying this out :)

The underlying X-Ray `Entity` should be being closed on [this line of `AWSXRaySpan`](https://github.com/skylight-ipv/opentracing-java-aws-xray/blob/master/src/main/java/io/opentracing/contrib/aws/xray/AWSXRaySpan.java#L383).

If you're working with the sources directly, can you try setting a breakpoint there?

**Comment by dmytro-bekuzarov** [comment]
It never enters that block, because [this condition](https://github.com/skylight-ipv/opentracing-java-aws-xray/blob/master/src/main/java/io/opentracing/contrib/aws/xray/AWSXRaySpan.java#L380) is false

**Comment by ashleymercer** [comment]
D'oh! Of course not - I am an idiot.

In the original (Scala) version of the code, I had a separate flag on `AWSXRaySpan` to keep track of whether `finish()` had been called yet or not. I was trying to be clever here by deferring to `Entity.isInProgress` - except, of course, the latter will *always* be true because we haven't finished it yet!

Will fix this now.

**Comment by ashleymercer** [comment]
Can you please fetch the new commit and try again? Thanks :)

**Comment by dmytro-bekuzarov** [comment]
It worked, thanks. 
I am testing it right now with Spring WebFlux. So far so good :)
