### ISSUE TITLE
Cross Process Propagation?

### ISSUE THREAD

**Issue by will-sargent-eero** [skylight-ipv/opentracing-java-aws-xray#5]
I posted in https://github.com/aws/aws-xray-sdk-java/issues/95#issuecomment-536757507 because I'm using a non-servlet based web framework, and there's a note:

```
calls between AWS services using the official SDK will already handle passing trace IDs across.
```

The official SDK doesn't have a framework independent way of pulling out data from an HTTP header -- even the "core" contains the servlet API specific filter, rather than abstracting it:

https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/javax/servlet/AWSXRayServletFilter.java

The code seems to say that there's some standard HTTP headers "X-Amzn-Trace-Id" and segment ID: https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader but this is not compartmentalized functionality.

**Comment by ashleymercer** [comment]
Hi @will-sargent-eero - thanks for raising this. I didn't add support for cross-process propagation in the first version because, somewhat lazily, I didn't need it! 

The OpenTracing way of doing this is using [span injection and extraction](https://opentracing.io/docs/overview/inject-extract/) and it looks like it should be fairly straightforward. The standard allows for arbitrary "carrier" formats, but it seems like HTTP headers would be by far the most useful (and probably sufficient for most people?)

Would you be willing / able to have a go at a PR for this?

On a related note, the OpenTracing standard is being merged with another project (OpenCensus) and the new unified API will released as [OpenTelemetry](https://opentelemetry.io/about/), hopefully by the end of this year. My plan is to write an OpenTelemetry-compatible version of this library once the API is finalised.

**Comment by will-sargent-eero** [comment]
> Would you be willing / able to have a go at a PR for this?

Unfortunately I'm in the evaluation stage for distributed tracing solutions so it would be premature.  It would also mean going through OSS code release process and being at least partly responsible for maintaining it.

**Comment by ashleymercer** [comment]
@will-sargent-eero I had some time today and have just pushed a first version with support for context propagation: would you have time to try it out?

- the `inject` and `extract` methods are now implemented: in most cases, you'll get a single-valued map containing `X-Amzn-Trace-Id` in the standard format [1]

- constructing new `Span`s should work correctly in the case where the context has been injected externally, e.g. by having read some custom HTTP header from elsewhere

[1] https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

**Comment by will-sargent-eero** [comment]
I'll check it out, thank you!
